ant-media/Ant-Media-Server-Common

src/main/java/io/antmedia/datastore/db/IDataStore.java
src/main/java/io/antmedia/datastore/db/types/Broadcast.java
src/main/java/io/antmedia/muxer/MuxAdaptor.java

add stream specific mp4 setting

add stream specific mp4 setting

---

src/main/java/io/antmedia/muxer/MuxAdaptor.java

add broadcast

---

src/main/java/io/antmedia/muxer/MuxAdaptor.java

add null check

---

src/main/java/io/antmedia/muxer/MuxAdaptor.java

make method for mp4 setting evaluation

make method for mp4 setting evaluation

---

src/main/java/io/antmedia/muxer/HLSMuxer.java

Test codes are in enterprise edition

Bug fix https://github.com/ant-media/Ant-Media-Server/issues/701

---

src/main/java/io/antmedia/datastore/db/types/Licence.java

Add status to license

---

pom.xml

This PR updates Guava version to latest in order to remove a vulnerability.

Fix: update guava version

---

src/main/java/io/antmedia/datastore/db/DataStore.java
src/main/java/io/antmedia/datastore/db/types/ConferenceRoom.java

add Conference Room infrastructure

add Conference Room infrastructure

---

src/main/java/io/antmedia/muxer/Mp4Muxer.java
src/main/java/io/antmedia/muxer/MuxAdaptor.java

This PR enables Mp4Muxer in runtime.

Enabling mp4muxer in runtime

---

src/main/java/io/antmedia/muxer/IAntMediaStreamHandler.java
src/main/java/io/antmedia/muxer/MuxAdaptor.java

Call streamhandler when a new mux adaptor is created or removed.

Maintain mux adaptor list in application class

---

src/main/java/io/antmedia/muxer/IAntMediaStreamHandler.java
src/main/java/io/antmedia/muxer/MuxAdaptor.java

This reverts commit 8a532b1b92b7e7e73a2cf46302a4b5938ebe5ff8.

Revert "Maintain mux adaptor list in application class"

---

src/main/java/io/antmedia/AppSettings.java

add useWebRTCOriginalSettings

---

src/main/java/io/antmedia/muxer/IAntMediaStreamHandler.java
src/main/java/io/antmedia/muxer/MuxAdaptor.java

Call streamhandler when a new mux adaptor is created or removed.

Call streamhandler when a new mux adaptor is created or removed.

---

src/main/java/io/antmedia/muxer/IAntMediaStreamHandler.java
src/main/java/io/antmedia/muxer/MuxAdaptor.java

Call streamhandler when a new mux adaptor is created or removed

Call streamhandler when a new mux adaptor is created or removed

---

src/main/java/io/antmedia/datastore/db/types/ConferenceRoom.java

change date format

---

src/main/java/io/antmedia/muxer/Muxer.java

Reverts ant-media/Ant-Media-Server-Common#135

Revert "Changed MP4 File Datetime type."

---

src/main/java/io/antmedia/muxer/Mp4Muxer.java

We fix it on muxer level because otherwise we need to always
do check on encoders for each muxer

Fix the audio/video synch issues at muxer level

---

src/main/java/io/antmedia/AppSettings.java
src/main/java/io/antmedia/muxer/MuxAdaptor.java

removed the old one
ne-time token publish and play mode

added two different settings for publish and play token control and

---

src/main/java/io/antmedia/AppSettings.java
src/main/java/io/antmedia/muxer/IAntMediaStreamHandler.java
src/main/java/io/antmedia/muxer/MuxAdaptor.java

https://github.com/ant-media/Ant-Media-Server/issues/2492

Remove the widthRTMPForwarding because it's calculated by aspect ratio

---

src/main/java/io/antmedia/muxer/MuxAdaptor.java
src/main/java/io/antmedia/muxer/Muxer.java
src/main/java/io/antmedia/muxer/RecordMuxer.java

Reverts ant-media/Ant-Media-Server-Common#218
Because enterprise test fails -> testPublishAndPlay_H264_ok_VP8_ok

Revert "check temp file existence"

---

src/main/java/io/antmedia/datastore/db/DataStore.java

java.lang.IllegalArgumentException: fromIndex(50) > toIndex(0)

Fix the illegalStateExceptin in DB

---

src/main/java/io/antmedia/muxer/MuxAdaptor.java

Related issue:
https://github.com/ant-media/Ant-Media-Server/issues/2658

change is recording set place

---

src/main/java/io/antmedia/muxer/Muxer.java

This PR fixes https://github.com/ant-media/Ant-Media-Server/issues/2622

Added milliseconds to mp4 date time

---

src/main/java/org/red5/server/net/rtmp/RTMPHandler.java

About https://github.com/ant-media/Ant-Media-Server/issues/2578

Accept streams having streamId starting with / by removing first char

---

src/main/java/io/antmedia/muxer/MuxAdaptor.java

https://github.com/ant-media/Ant-Media-Server/issues/2965

Rtmp analyze time

---

src/main/java/io/antmedia/AppSettings.java
src/main/java/io/antmedia/muxer/MuxAdaptor.java

Fix https://github.com/ant-media/Ant-Media-Server/issues/3071

Add dashHttpEndpoint in app settings

---

src/main/java/io/antmedia/datastore/db/types/Broadcast.java
src/main/java/io/antmedia/muxer/IAntMediaStreamHandler.java
src/main/java/io/antmedia/muxer/MuxAdaptor.java

https://github.com/ant-media/Ant-Media-Server/issues/3213

adds publishType parameter to broadcast object

---

src/main/java/io/antmedia/muxer/RtmpMuxer.java

It solves the issue https://github.com/ant-media/Ant-Media-Server/issues/3201

added synchronized for writeHeader and writeTrailer

---

src/main/java/io/antmedia/muxer/MuxAdaptor.java
src/main/java/io/antmedia/settings/IServerSettings.java

https://github.com/ant-media/Ant-Media-Server/issues/2969

Refactor codes for fixing the enterprise failure #2969

---

src/main/java/io/antmedia/muxer/Muxer.java

Make static DATE_TIME_PATTERN string

Make static DATE_TIME_PATTERN string

---

src/main/java/io/antmedia/muxer/RtmpMuxer.java

This PR fixes #https://github.com/ant-media/Ant-Media-Server/issues/3201

Fix write_trailer crash by checking if header is written
